[package]
name = "cg955gtr/partcache"
description = "A linked list based part cache class written in strict Luau."
version = "1.0.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
